### ISSUE TITLE
Registrierung Apotheke

### ISSUE THREAD

**Issue by simkoc** [kallle/pharmabus#9]
Abhängigkeiten:
+ Apotheke hat Internet

Annahmen:
+ Apotheke ist wirklich der der er ausgibt zu sein (keine Fake)

Schritte:
1. User geht auf das Registrierungsformular und füllt aus
   + Name
   + Addresse
   + Tel. Nummer
   + pwd
2. [Server] legt intern [Apotheke] an

**Comment by leeN** [comment]
Wieso legt der Server einen Patient an, wenn man eine Apotheke registriert?

**Comment by simkoc** [comment]
ist erledigt und getestet mit dem neuen schema
